# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm
  mappings:
    product_image:
      uri_prefix: /images/products
      upload_destination: '%kernel.project_dir%/public/images/products'
      namer: vich_uploader.namer_origname
      # lifecycle events
      inject_on_load:     false
      delete_on_update:   true
      delete_on_remove:   true